plugins {
    id 'java-library'
    id 'maven-publish'
    id 'com.gradleup.shadow' version '9.6.1'
    id 'io.github.ben-manes.versions' version '0.64.0'
}

group = 'me.sirimperivm'
description = "DatabaseFramework"

def versionFile = file("$projectDir/version.txt")
def distDir = file("$projectDir/dist")

if (!versionFile.exists()) {
    versionFile.text = "0.0.0"
}

version = versionFile.text.trim()

tasks.register("incrementVersion") {
    def file = versionFile
    doLast {
        def (major, minor, patch) = file.text.trim().tokenize('.').collect { it as int }
        def newVersion = "${major}.${minor}.${patch + 1}"
        file.text = newVersion
        println "✅ Version incremented to: ${newVersion}"
    }
}

tasks.register("distribute", Copy) {
    from tasks.named('shadowJar').flatMap { it.archiveFile }

    def targetName = "${project.description}-latest.jar"
    into distDir
    rename { targetName }

    def target = new File(distDir, targetName).path
    doLast {
        println "📦 JAR File Distributed As: ${target}"
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    withSourcesJar()
}

repositories {
    mavenCentral()
}

def lombokVersion = "1.18.48"

dependencies {
    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"

    api 'com.zaxxer:HikariCP:7.1.0'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}

shadow {
    addShadowVariantIntoJavaComponent = false
}

tasks.shadowJar {
    archiveClassifier.set('all')

    relocate 'com.zaxxer', 'me.sirimperivm.libs.com.zaxxer'

    exclude('META-INF/*.SF', 'META-INF/*.DSA', 'META-INF/*.RSA')
    exclude('org/slf4j/**', 'META-INF/maven/org.slf4j/**')
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
        }
    }
}

tasks.build {
    dependsOn tasks.distribute
}
